# Turn on output to file
json_output: true
json_include_output_property: true
json_include_tags_property: true

# config log file to output
file_output:
  enabled: true
  keep_alive: false
  filename: /var/log/falco/falco_events.json_include_output_property

# Tắt output ra stdout đỡ rối (option)
stdout_output:
  enabled: false

  # các cấu hình khác giữ mặc định
  log_stderr: true
  log_syslog: false
  webserver:
    enabled: false
  program_output:
    enabled: false
