rules_files:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml

load_plugins: [container]

plugins:
  - name: container
    library_path: libcontainer.so

json_output: true
json_include_output_property: true
json_include_tags_property: true

file_output:
  enabled: true
  keep_alive: false
  filename: /var/log/falco/falco_events.json

stdout_output:
  enabled: false

log_stderr: true
log_syslog: false

webserver:
  enabled: false

program_output:
  enabled: false
  program: echo
