# Turn on output to file
json_output: true
json_include_output_property: true
json_include_tags_property: true

# config log file to output
file_output:
  enabled: true
  keep_alive: false
  filename: /var/log/falco/falco_events.json_include_output_property
